[build-system]
requires = ["setuptools>=81", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "owm"
dynamic = ["version"]
description = "OpenWeatherMap CLI client"
readme = "README.md"
license = { text = "GPL-3.0" }
requires-python = ">=3.13"
authors = [
    {name = "Pablo Alejandro Carravetti", email = "gpablinux@gmail.com"}
]
dependencies = [
    "requests",
]

[project.urls]
Homepage = "https://github.com/PabliNet/owm"
Repository = "https://github.com/PabliNet/owm"
Issues = "https://github.com/PabliNet/owm/issues"

[project.scripts]
owm = "owm.cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["owm*"]

[tool.setuptools.package-data]
owm = ["locale/*/LC_MESSAGES/owm.mo"]

[tool.setuptools.dynamic]
version = {file = "VERSION"}
